version: "3.5"

services:
  db:
    image: mariadb:10.11
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wp_default
  wordpress:
    depends_on:
      - db
    build: ./
    volumes:
      - "site-data:/var/www/wp-content"
    ports:
      - "8123:80"
    environment:
      DB_HOST: db
      DB_PASSWORD: wordpress
      DB_NAME: wordpress
      DB_USER: wordpress
      WORDPRESS_SITE_URL: https://source.it-live-blog.com
      FS_METHOD: direct
      # For debugging only:
      #WP_DEBUG: "true"
      #WP_DEBUG_DISPLAY: "true"
    networks:
     - wp_default
     - npm_default
volumes:
  db-data:
  site-data:

networks:
  wp_default:
    external: true
 npm_default:
    external: true
