version: "3.5"

services:
  db:
    image: mariadb:10.11
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
    networks:
      - wp_default
      
  wordpress:
    depends_on:
      - db
    build: ./
    volumes:
      - "site-data:/var/www/wp-content"
#    ports:
#      - "8123:80"
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PASSWORD: $DB_PASS
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      WORDPRESS_SITE_URL: $URL
      FS_METHOD: direct
      # For debugging only:
      #WP_DEBUG: "true"
      #WP_DEBUG_DISPLAY: "true"
    networks:
     - wp_default
     - npm_default
volumes:
  db-data:
  site-data:

networks:
  wp_default:
    external: true
 npm_default:
    external: true
